#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} --config "$CFG" open profile --screen 0
  ${EWW} --config "$CFG" open system --screen 0
  ${EWW} --config "$CFG" open clock --screen 0
  ${EWW} --config "$CFG" open uptime --screen 0
  ${EWW} --config "$CFG" open music --screen 0
  ${EWW} --config "$CFG" open github --screen 0
  ${EWW} --config "$CFG" open reddit --screen 0
  ${EWW} --config "$CFG" open twitter --screen 0
  ${EWW} --config "$CFG" open youtube --screen 0
  ${EWW} --config "$CFG" open weather --screen 0
  ${EWW} --config "$CFG" open apps --screen 0
  ${EWW} --config "$CFG" open mail --screen 0
  ${EWW} --config "$CFG" open logout --screen 0
  ${EWW} --config "$CFG" open sleep --screen 0
  ${EWW} --config "$CFG" open reboot --screen 0
  ${EWW} --config "$CFG" open poweroff --screen 0
  ${EWW} --config "$CFG" open folders --screen 0

}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} --config "$CFG" close \
					background profile system clock uptime music github \
					reddit twitter youtube weather apps mail logout sleep reboot poweroff folders
	rm "$FILE"
fi
