#!/bin/bash
# current_hour=$(date +%H)
current_hour = $(sw)
# Define the paths for DIR

# Check if it's later than 11pm or earlier than 6am
if [ "$(sw)" == 1 ]; then
    DIR="$HOME/.config/hypr/bg"
else
    DIR="$HOME/progs/aesthetic-wallpapers/images"
fi

PICS=($(ls ${DIR}))
RANDOMPICS=${PICS[ $RANDOM % ${#PICS[@]} ]}

if [[ $(pidof swaybg) ]]; then
  pkill swaybg
fi

swaybg -m fill -i ${DIR}/${RANDOMPICS}
# swww img ${DIR}/${RANDOMPICS} --transition-type center
notify-send "${RANDOMPICS}"
