#!/bin/bash

#wallpaper fetcher and wallpaper rotator
#type "var" in a terminal to change settings - example
#variety &

number_file="/home/red/.config/hypr/switch.txt"
echo "0" > "$number_file"
SCRIPTSDIR=$HOME/.config/hypr/scripts

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

# Apply themes
${SCRIPTSDIR}/gtkthemes &

# Lauch notification daemon (mako)
${SCRIPTSDIR}/notifications &

# Lauch statusbar (waybar)
${SCRIPTSDIR}/statusbar &

# Xauthority
${SCRIPTSDIR}/xauthority &

dex $HOME/.config/autostart/arcolinux-welcome-app.desktop &

#insync start &
#dropbox &
#telegram-desktop &
#discord &
# nm-applet --indicator
sudo tlp start
sudo tlp setcharge
pypr
sudo modprobe snd_aloop

