#!/bin/bash

# Define the file to store the number
number_file="/home/red/.config/hypr/switch.txt"

# Check if the first argument is "-s" and set the number accordingly
if [ "$1" == "-s" ]; then
  if [ -n "$2" ]; then
    echo "$2" > "$number_file"
    echo "Number set to: $2"
  else
    echo "Please provide a number to set."
  fi
else
  if [ -e "$number_file" ]; then
    number=$(cat "$number_file")
    echo "$number"
  else
    echo "Number is not set. Use 'sw.sh -s <number>' to set the number."
  fi
fi

